version: '3.9'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: magicow
      MYSQL_PASSWORD: magicow
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - magicow:/var/lib/mysql
# Names our volume
volumes:
  magicow:
